import java.util.Arrays;

/**
 * The Vector class is an encapsulation of a Vector with many double components.
 * <p>
 * Vectors are immutable.
 * <p>
 * This work complies with the JMU Honor Code.
 *
 * @author Ryan Showalter
 * @version 1
 */
public class Vector
{

  private double[] components;

  /**
   * Create a vector with the given components.
   *
   * @param components the components of the vector
   */
  public Vector(double[] components)
  {
    this.components = components.clone();
  }

  /**
   * Get an array representation of this Vector.
   *
   * @return an array representation of this Vector
   */
  public double[] toArray()
  {
    return components.clone();
  }

  /**
   * Get the vector resulting from scalar multiplying this Vector by the given scalar.
   *
   * @param scalar the scalar to multiply by
   * @return the result of scalar multiplication
   */
  public Vector scale(double scalar)
  {
    double[] newComponents = Arrays.stream(components).map((x) -> scalar * x).toArray();
    return new Vector(newComponents);
  }

  @Override public String toString()
  {
    return Arrays.toString(components);
  }

  /**
   * Get the result of adding another Vector to this Vector.
   *
   * @param addend the Vector to add to this one
   * @return the result of adding
   */
  public Vector add(Vector addend)
  {
    if (this.components.length != addend.components.length)
    {
      throw new IllegalArgumentException(
          "Vectors must have the same number of components to be added.");
    }

    double[] resultComponents = new double[this.components.length];

    for (int i = 0; i < resultComponents.length; i++)
    {
      resultComponents[i] = this.components[i] + addend.components[i];
    }

    return new Vector(resultComponents);
  }

  /**
   * Determine whether this Vector is equal to the given Object.
   * <p>
   * This method was generated by IntelliJ IDEA.
   *
   * @param o the other Object
   * @return whether this object is equal to o
   */
  @Override public boolean equals(Object o)
  {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    Vector vector = (Vector) o;
    return Arrays.equals(components, vector.components);
  }

  /**
   * Get the hashCode of this Vector.
   * <p>
   * This method was generated by IntelliJ IDEA.
   *
   * @return the hashCode of this Vector
   */
  @Override public int hashCode()
  {
    return Arrays.hashCode(components);
  }
}
